# Generated by Django 3.2.5 on 2021-10-24 05:02

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('partners', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('birth_date', models.DateField(null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_image', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=9, null=True)),
                ('address', models.CharField(max_length=75, null=True)),
                ('organization', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_number', models.CharField(max_length=75, null=True)),
                ('language', models.CharField(choices=[('AF', 'Afrikaans'), ('SQ', 'Albanian'), ('AR', 'Arabic'), ('HY', 'Armenian'), ('EU', 'Basque'), ('BN', 'Bengali'), ('BG', 'Bulgarian'), ('CA', 'Catalan'), ('KM', 'Cambodian'), ('ZH', 'Chinese'), ('HR', 'Croatian'), ('CS', 'Czech'), ('DA', 'Danish'), ('NL', 'Dutch'), ('EN', 'English'), ('ET', 'Estonian'), ('FJ', 'Fiji'), ('FI', 'Finnish'), ('FR', 'French'), ('KA', 'Georgian'), ('DE', 'German'), ('EL', 'Greek'), ('GU', 'Gujarati'), ('HE', 'Hebrew'), ('HI', 'Hindi'), ('HU', 'Hungarian'), ('IS', 'Icelandic'), ('ID', 'Indonesia'), ('GA', 'Irish'), ('IT', 'Italian'), ('JA', 'Japanese'), ('JW', 'Javanese'), ('KO', 'Korean'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LT', 'Lithuania'), ('MK', 'Macedonia'), ('MS', 'Malay'), ('ML', 'Malayalam'), ('MT', 'Maltese'), ('MI', 'Maori'), ('MR', 'Marathi'), ('MN', 'Mongolian'), ('NE', 'Nepali'), ('NO', 'Norwegian'), ('FA', 'Persian'), ('PL', 'Polish'), ('PT', 'Portugues'), ('PA', 'Punjabi'), ('QU', 'Quechua'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SM', 'Samoan'), ('SR', 'Serbian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('ES', 'Spanish'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TH', 'Thai'), ('BO', 'Tibetan'), ('TO', 'Tonga'), ('TR', 'Turkish'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VI', 'Vietnames'), ('CY', 'Welsh'), ('XH', 'Xhosa')], default='EN', max_length=75, null=True)),
                ('bio', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=2500, null=True)),
                ('seller', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('reject', models.BooleanField(null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.category')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
