# Generated by Django 3.2.5 on 2021-10-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Account', (('Unsubscribe from Miver emails', 'Unsubscribe from Miver emails'), ('I want to change my username', 'I want to change my username'), ('I have another Miver account', 'I have another Miver account'), ('Other', 'Other'))), ('Buying', (('I can not find what I need on Miver', 'I can not find what I need on Miver'), ('Miver is complicated or hard to use', 'Miver is complicated or hard to use'), ('Negative experience with seller/s', 'Negative experience with seller/s'), ('I am unhappy with Mivers policies', 'I am unhappy with Miver policies'), ('other', 'other')))], default='male', max_length=50)),
                ('detail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
